# [Machine Learning] Supervised Learning

## Support Vector Machine Regression

### Load Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

## Load Dataset

In [2]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df = pd.read_csv(path)

In [3]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

## Split Data

In [4]:
x = df.drop('price', axis=1)
y = df['price']

In [5]:
x.shape, y.shape

((7120, 107), (7120,))

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [7]:
x_train.shape, x_test.shape

((5696, 107), (1424, 107))

In [8]:
y_train.shape, y_test.shape

((5696,), (1424,))

## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_trainn = sc.transform(x_train)
x_test = sc.transform(x_test)

## Support Vector Regression Model

In [10]:
from sklearn.svm import SVR

In [11]:
# rbf
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(x_train, y_train)
svr_rbf.score(x_test,y_test)

-0.4412226965463384

In [12]:
# linear
"""svr_linear = SVR(kernel='linear')
svr_linear.fit(x_train, y_train)
svr_linear.score(x_test,y_test)"""

"svr_linear = SVR(kernel='linear')\nsvr_linear.fit(x_train, y_train)\nsvr_linear.score(x_test,y_test)"

In [13]:
# poly
"""svr_poly = SVR(kernel='poly', degree=2)
svr_poly.fit(x_train, y_train)
svr_poly.score(x_test,y_test)"""

"svr_poly = SVR(kernel='poly', degree=2)\nsvr_poly.fit(x_train, y_train)\nsvr_poly.score(x_test,y_test)"

## Predict The Value

In [14]:
x_test[0]

array([-0.44422611,  0.54630035, -0.34334897, -0.55044507, -0.72383255,
        0.57680968, -0.47233992, -0.25703648,  0.50597314, -0.18727461,
       -0.16162122, -0.15580825, -0.1288342 , -0.13023539, -0.12812824,
       -0.12234347,  7.59747652, -0.12741862, -0.12234347, -0.10909925,
       -0.1082724 , -0.1082724 , -0.11472827, -0.10743948, -0.09218776,
       -0.09315135, -0.08823182, -0.08923672, -0.09023078, -0.08195215,
       -0.08514823, -0.0830308 , -0.08514823, -0.07276497, -0.07975227,
       -0.07975227, -0.07749158, -0.0739743 , -0.06901264, -0.0751646 ,
       -0.07153563, -0.0751646 , -0.0751646 , -0.0751646 , -0.07749158,
       -0.07633675, -0.07276497, -0.06901264, -0.0739743 , -0.07276497,
       -0.07028523, -0.06504853, -0.0677166 , -0.0677166 , -0.0677166 ,
       -0.06504853, -0.07153563, -0.06367332, -0.06226825, -0.06639573,
       -0.06226825, -0.06367332, -0.06504853, -0.06504853, -0.06504853,
       -0.06083125, -0.05785186, -0.06639573, -0.06226825, -0.06

In [16]:
svr_rbf.predict([x_test[0]])

array([27.09279033])

In [17]:
y_pre = svr_rbf.predict(x_test)
y_pre

array([27.09279033, 27.0883579 , 27.08538017, ..., 27.08805527,
       27.09538243, 27.08964172])

In [18]:
y_test

960      47.0
132      60.0
2431     65.0
2229    325.0
4503     60.0
        ...  
4970     48.0
553     205.0
1397     56.5
4056     26.0
1817     49.0
Name: price, Length: 1424, dtype: float64

In [19]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pre)
rmse = np.sqrt(mse)

In [20]:
print('MSE is: ', mse)
print('RMSE is: ', rmse)

MSE is:  16362.416956581663
RMSE is:  127.9156634528456
